<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Engine\ApiBundle\Form\Type\BookType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Engine/ApiBundle/Form/Type/BookType.php';

return $this->services['App\\Engine\\ApiBundle\\Form\\Type\\BookType'] = new \App\Engine\ApiBundle\Form\Type\BookType();
