<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Engine\ApiBundle\Validator\Constraints\ContainsAlphanumericValidator' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidator.php';
include_once $this->targetDirs[3].'/src/Engine/ApiBundle/Validator/Constraints/ContainsAlphanumericValidator.php';

return $this->services['App\\Engine\\ApiBundle\\Validator\\Constraints\\ContainsAlphanumericValidator'] = new \App\Engine\ApiBundle\Validator\Constraints\ContainsAlphanumericValidator();
