<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\DanTestCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/DanTestCommand.php';

$this->services['App\\Command\\DanTestCommand'] = $instance = new \App\Command\DanTestCommand();

$instance->setName('dan:test-command');

return $instance;
