<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2puyii\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2puyii/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN2puyii.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN2puyii\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerN2puyii\srcDevDebugProjectContainer([
    'container.build_hash' => 'N2puyii',
    'container.build_id' => '27ae74fc',
    'container.build_time' => 1580298607,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2puyii');
